# Generated by Django 5.0.4 on 2024-09-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=False, verbose_name='Is therapist'),
        ),
    ]
