# Generated by Django 5.1.1 on 2024-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_user_is_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
