# Generated by Django 5.1.1 on 2024-10-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
