# Generated by Django 5.1.1 on 2024-10-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
