# Generated by Django 5.1.1 on 2024-10-06 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garden.category'),
        ),
    ]
