# Generated by Django 5.1.1 on 2024-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_service_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_educator',
            field=models.BooleanField(default=False, null=True, verbose_name='Is educator'),
        ),
    ]
