# Generated by Django 5.1.1 on 2024-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_schedule_user_is_educator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_educator',
            field=models.BooleanField(default=False, verbose_name='Is educator'),
        ),
    ]
