# Generated by Django 5.1.1 on 2024-10-07 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_alter_user_is_educator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='category',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='educator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educator_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garden.service'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
