# Generated by Django 5.0.4 on 2024-10-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0013_notavailabledate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotAvailableDate',
        ),
    ]
