# Generated by Django 5.0.4 on 2024-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0019_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
